### PR TITLE
Default to completing files in Zsh

### PR DESCRIPTION
**Pull request by segevfiner**
This is similar to Bash's `-o default` that is currently used.

### CODE REVIEW

**Comment by glehmann** [comment]
It doesn't seem to change the behavior here. Would you have an example that I can test?

**Comment by segevfiner** [comment]
> It doesn't seem to change the behavior here. Would you have an example that I can test?

### Source
```py
#!/usr/bin/env python
import click
import click_completion

click_completion.init()


@click.command()
@click.argument("name-file", type=click.File("r"))
def f(name_file):
    print "Hello, {}!".format(name_file.read())


if __name__ == "__main__":
    f()
```

### On master branch
```sh
➜ eval "$(_HELLO_COMPLETE=source-zsh hello)"
➜ hello <tab><tab><tab> # Nothing... sigh...
```

### This PR
```sh
➜ eval "$(_HELLO_COMPLETE=source-zsh hello)"
➜ hello <tab>
# File names are suggested
```

Which is what `-o default` does in Bash, suggesting file names if no completions are generated.

**Comment by glehmann** [comment]
ok, works for me too — I just had the wrong version tested…

**Comment by glehmann** [comment]
thanks!

**Pull request merged**
