### PR TITLE
completion with "inner" substrings

### LINKED ISSUE #13: zsh completion with "inner" substrings
I have a Choice option with the following values: "kotlin-rest-spring-boot-local", "kotlin-rest-spring-boot", "java-rest-spring-boot"

```
@click.option('--template', "template_key", type=click.Choice(["kotlin-rest-spring-boot-local", "kotlin-rest-spring-boot", "java-rest-spring-boot"]))
def create(template_key=None):
    pass
```

when I hit 'tab'for the first time at

    compdummy --template <tab>

I get 

    compdummy --template -rest-spring

because '-rest-spring' is a common substring. Hitting 'tab' again, nothing happens because:

```
def choice_complete(self, ctx, incomplete):
    return [c for c in self.choices if c.startswith(incomplete)]
```

only checks for 'startswith'.

If I replace the above code with:

```
def choice_complete(self, ctx, incomplete):
    return [c for c in self.choices if incomplete in c]
```

everything works fine

### PR DESCRIPTION
**Pull request by kontrafiktion**
Fixes #13

### CODE REVIEW

**Comment by Konubinix** [comment]
Thank you for the PR.
As far as I am concerned, this is ok. I think bash-complete doesn't mind this change for it already checks the completions start with the prefix.
Just waiting for @glehmann to discuss further before merging, just in case.

**Comment by Konubinix** [comment]
Actually, click_completion already provide you with this customization.
With my recent push.
```
from click_completion import init
def match_incomplete(choice, incomplete):
    return incomplete in choice
init(match_incomplete=match_incomplete)
```

**Comment by Konubinix** [comment]
@kontrafiktion How did it go?

**Comment by kontrafiktion** [comment]
Works for me. You can forget my PR

**Pull request closed without merging**
